from social.apps.django_app.middleware import SocialAuthExceptionMiddleware
SocialAuthExceptionMiddleware  # placate pyflakes
